# Generated by Django 2.2.13 on 2020-12-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201213_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main',
            field=models.BooleanField(blank=True, null=True, verbose_name='Раздел'),
        ),
    ]
