# Generated by Django 2.2.13 on 2020-12-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20201214_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Main_category', 'verbose_name_plural': 'Main_categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.MainCategory', verbose_name='Основная категория'),
        ),
    ]
