# Generated by Django 2.2.13 on 2020-12-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201215_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.MainCategory', verbose_name='Main category'),
        ),
    ]
