# Generated by Django 2.2.13 on 2020-12-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20201215_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_id',
            field=models.ManyToManyField(related_name='articles', to='webapp.Category', verbose_name='Категория'),
        ),
    ]
